### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by kiwi0fruit** [kiwi0fruit/misc#2]

**Comment by kiwi0fruit** [comment]
* [x] ~[Image size bug in MPP](https://github.com/atom-community/markdown-preview-plus/issues/405)~
* [ ] [Save As PDF makes font colors darker](https://github.com/atom-community/markdown-preview-plus/issues/393)
* [ ] [Empty lines in code blocks dissapper](https://github.com/atom-community/markdown-preview-plus/issues/398)
* [ ] Check cross-references links

**Comment by kiwi0fruit** [comment]
# Tune MPP

* [x] ~do not forget about [this](https://github.com/kiwi0fruit/misc/commit/70609c253629c09d51dc35076e69755d31d2d869) - add font settings to GUI~
* [x] check if [code highlighter spaces problem](https://github.com/atom-haskell/atom-highlights/pull/1) is solved
* [x] check if `data:image/`now works
* [x] find out how to tune MathJax and tune it
* [x] fix main .less file. Move fonts definitions there too and take into account  changes:
    `.markdown-preview:not([data-use-github-style])` ->  
    `markdown-preview-plus-view:not([data-use-github-style])` changes
* [x] `@mjx-mono-font-size: 80%;`
* [ ] ~enhance [PDF print](https://github.com/atom-community/markdown-preview-plus/issues/397)~
  * ~.pdf.7z~
      * ~.phone.pdf~
      * ~.tablet.pdf~
      * ~.desktop.pdf~
      * ~.A4.pdf~

* [ ] PR [MPP Patch](https://github.com/kiwi0fruit/misc/tree/master/mpp)

https://github.com/atom-community/markdown-preview-plus/blob/master/CONTRIBUTING.md

**Comment by kiwi0fruit** [comment]
No multiple pdf. Have one that looks good on tablet, good on smartphone horizontal. Images and tables are of the same size as text nody. But if I set style to 100% the table would take all horizontal space (which is wider that text body).

**Comment by kiwi0fruit** [comment]
https://github.com/atom-community/markdown-preview-plus/issues/441
